#!/usr/bin/env bash

rm /usr/bin/firefox > /dev/null 2>&1
ln -s /opt/firefox-beta/firefox /usr/bin/firefox

#chmod 644 /usr/share/applications/firefox-beta.desktop
#chown root:root /usr/share/applications/firefox-beta.desktop
#update-desktop-database -q

#echo "Please restart any running instances of Firefox."
